# Generated by Django 4.2.2 on 2024-05-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="users",
            name="token",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Token"
            ),
        ),
    ]
