# Generated by Django 4.2.2 on 2024-05-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_users_options_users_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="token",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Token"
            ),
        ),
    ]
