# Generated by Django 5.0.3 on 2024-04-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="text_area",
            field=models.TextField(verbose_name="Текст"),
        ),
    ]
