# Generated by Django 5.0.3 on 2024-04-17 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_text_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="actual_version_indicator",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Статус публикации"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime.now,
                null=True,
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="number_of_views",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="URL"
            ),
        ),
    ]
