# Generated by Django 5.0.3 on 2024-04-03 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_image_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_data.json',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата последнего изменения'),
        ),
    ]
