# Generated by Django 5.0.3 on 2024-04-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_remove_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=50, verbose_name="Страна")),
                ("identity_nalog_number", models.IntegerField(verbose_name="ИНН")),
                ("addres", models.TextField(verbose_name="Адрес")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
