# Generated by Django 5.0.3 on 2024-04-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_contactsdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsdata",
            name="slug",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="URL"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="URL"
            ),
        ),
    ]
