# Generated by Django 5.0.3 on 2024-05-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_versionproduct"),
    ]

    operations = [
        migrations.RenameField(
            model_name="versionproduct",
            old_name="is_active",
            new_name="is_active_version",
        ),
        migrations.AlterField(
            model_name="versionproduct",
            name="number_of_version",
            field=models.PositiveIntegerField(verbose_name="Номер версии продукта"),
        ),
    ]
