# Generated by Django 4.2.2 on 2024-05-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("cancel_product", "Can delete product"),
                    ("change_product_description", "Can change product description"),
                    ("change_category_product", "Can change category product"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
